name: ci

# Controls when the workflow will run
on:
  # Build weekly
  # schedule:
  #   - cron: '0 21 * * 0'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # tags:
  #   - [0-9]+.[0-9]+.[0-9]+*
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# JOBS section
jobs:
  # Linting section
  linting-alpine:
    name: linting-alpine
    runs-on: ubuntu-latest
    steps:
      -
        name: Linting Dockerfile.alpine
        uses: actions/checkout@v3 
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile.alpine

  linting-ubuntu:
    name: linting-ubuntu
    runs-on: ubuntu-latest
    steps:
      -
        name: Linting Dockerfile.ubuntu
        uses: actions/checkout@v3
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile.ubuntu

# Alpine section
  build-alpine:
    name: build-alpine
    runs-on: ubuntu-latest
    needs: linting-alpine
    steps:
      -
        name: Alpine - Checkout 
        uses: actions/checkout@v3
      -
        name: Alpine - Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Alpine - Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Alpine - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Alpine - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:alpine-latest, ${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:2.0.0, ${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:latest
          labels: "alpine"
          # labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache,mode=max

# Ubuntu section
  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    needs: linting-ubuntu
    steps:
      -
        name: Ubuntu - Checkout 
        uses: actions/checkout@v3
      -
        name: Ubuntu - Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Ubuntu - Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Ubuntu - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Ubuntu - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:ubuntu-latest, ${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:1.0.0
          labels: "ubuntu"
          # labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache,mode=max